-- MySQL Script generated by MySQL Workbench
-- Fri Dec  1 10:33:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema movies_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `movies_db` ;

-- -----------------------------------------------------
-- Schema movies_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movies_db` DEFAULT CHARACTER SET utf8 ;
USE `movies_db` ;

-- -----------------------------------------------------
-- Table `movies_db`.`title_basics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies_db`.`title_basics` ;

CREATE TABLE IF NOT EXISTS `movies_db`.`title_basics` (
  `tconst` INT NOT NULL,
  `primary_title` LONGTEXT NULL,
  `start_year` FLOAT NULL,
  `runtime` INT NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW() ON UPDATE NOW(),
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies_db`.`ratings` ;

CREATE TABLE IF NOT EXISTS `movies_db`.`ratings` (
  `tconst` INT NOT NULL AUTO_INCREMENT,
  `average_rating` INT NULL,
  `number_of_votes` INT NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies_db`.`genres` ;

CREATE TABLE IF NOT EXISTS `movies_db`.`genres` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(45) NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`title_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies_db`.`title_genres` ;

CREATE TABLE IF NOT EXISTS `movies_db`.`title_genres` (
  `tconst` INT NOT NULL AUTO_INCREMENT,
  `genre_id` INT NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
